M48
; DRILL file {KiCad 9.0.1} date 2025-04-27T01:09:33-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-27T01:09:33-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X83.368Y-97.899
X83.368Y-104.899
T2
X82.042Y-89.154
X82.042Y-131.826
X144.018Y-89.154
M30
